FROM arm32v7/ubuntu
MAINTAINER zella

ARG VERSION

ENV DOWNLOAD_LINK=https://github.com/YouROK/TorrServer/releases/download/$VERSION/TorrServer-linux-arm7

#building arm on x86
COPY qemu-arm-static /usr/bin
RUN chmod +x /usr/bin/qemu-arm-static

RUN apt-get update && apt-get install -y wget && \
    mkdir /torrserver/ && cd /torrserver/ && mkdir /db && \
    wget -O TorrServer -P /torrserver/ "$DOWNLOAD_LINK" && \
    chmod +x /torrserver/TorrServer


EXPOSE 8090

ENTRYPOINT ["/torrserver/TorrServer"]
CMD ["--path", "/torrserver/db"]
